.PHONY: clean All

All:
	@echo "----------Building project:[ Section4 - Debug ]----------"
	@cd "Project1" && "$(MAKE)" -f  "Section4.mk"
clean:
	@echo "----------Cleaning project:[ Section4 - Debug ]----------"
	@cd "Project1" && "$(MAKE)" -f  "Section4.mk" clean
